### ISSUE TITLE
admin page

### ISSUE THREAD

**Issue by Obadh** [Obadh/recipesbook#10]

**Comment by M3kH** [comment]
When I'm gonna visit the **_Application_** through the url: **http(s)://{{MYAPPURL}}/admin** I will be asking for a password and then after that I'm gonna see the page:
![Admin Pannel](https://raw.githubusercontent.com/Obadh/recipesbook/master/mockups/Admin%20page.jpg)

**TODOS:**
I'm expecting then that this issue is gonna be divided in two parts:

**FRONTEND**
- [ ] Create password asking field
- [ ] Create the form
  - [ ] Input title
  - [ ] Textarea description
  - [ ] Checkbox list of ingredients
  - [ ] Upload field for image
  - [ ] Url field for image
  - [ ] Input field for Video
- [ ] Style the page according with the customer
- [ ] Add ingredient input (ajax)

**BACKEND**
- [ ] /admin/createRecepies is gonna expect an OBJ `{ title: STRING, desc: STRING, ingredients ARRAY, img: STRING, video: STRING }` and should insert in the database.
- [ ] /admin/createIngredient is gonna expect an OBJ `{ name: STRING, category: INTEGER, img: STRING }`
- [ ] /admin/imageUpload should accept an OBJ `{url: STRING}`
- [ ] /admin/imageUpload should download the image and provide a local server url like: `{url: {{MYAPP_URL}}/images/{{HASH}}.{{IMAGE_TYPE}}`.
- [ ] /admin/imageUpload POST Request MultiType
